language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
#  - DJANGO="Django==1.2"
  - DJANGO="Django==1.3.5"
  - DJANGO="Django==1.4.3"
  - DJANGO="git+git://github.com/django/django.git@master#egg=django"

# command to install dependencies
install: ./.travis-install.sh

# command to run tests
script: python runtests.py
