
language: python
python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.2
  - DJANGO_VERSION=1.3
  - DJANGO_VERSION=1.4

# command to install dependencies
install: pip install mock==0.7.2 Django==$DJANGO_VERSION --use-mirrors

# command to run tests
script: python runtests.py
