language: python
python:
  - "2.6"
  - "2.7"

env:
#  - DJANGO="Django==1.2"
  - DJANGO="Django==1.3"
  - DJANGO="git+git://github.com/django/django.git@master#egg=django==1.4c2"

# command to install dependencies
install: pip install mock==0.7.2 $DJANGO --use-mirrors

# command to run tests
script: python runtests.py
